### ISSUE TITLE
create userdata/MUBoard/postings/firstimage automatically

### ISSUE THREAD

**Issue by MrMontesa** [Portugao/MUBoard#43]
Hey,
instead of giving an error message on installing MUBoard the autocreation of folder userdata/MUBoard/postings/firstimage would be nice.
php mkdir or there is already an internal ZK function for that. I would recommend to check with other modules adding data to userdata.
Thanks

**Comment by Portugao** [comment]
The next version for Zikula 1.4.6 will have it.
