### ISSUE TITLE
Script to move data Dizkus 3.1 to MUBoard

### ISSUE THREAD

**Issue by PierreNau** [Portugao/MUBoard#60]
I Michael,
As requested on the community forum.
Would you please let me know an email address to send you my dizkus tables.
Many Thanks.
Regards.
Pierre.

**Comment by Portugao** [comment]
Hi Pierre,
kontakt@webdesign-in-bremen.com

Greetings

**Comment by Portugao** [comment]
@PierreNau 
Did you get my email address?

**Comment by PierreNau** [comment]
Hi Michael,
Yes I did and I sent you the dizkus database on Tursday night at mailto:kontakt@webdesign-in-bremen.com through your web site.
Did you get it? Please confirm me.
If not, I shall send it tomorrow when back at home
Regards.
Pierre.

Envoyé de mon iPad

**Comment by Portugao** [comment]
Sorry. No I did not.
Regards Michael

**Comment by Portugao** [comment]
Correction. I did. It was on my account.
Thx for that.

Greetings Michael

**Comment by Portugao** [comment]
Close ticket.
See detail tickets.

**Comment by Portugao** [comment]
I think the script is complete.
Would be nice if you could test the actual repository.

**Comment by PierreNau** [comment]
Hi Michael,
I have tested the repository:
Database import is working perfectly wether selecting "all" or "category and forums" or "posts and answers"
However the results must be improved.

Hereafter screenshots that speak by themselves:
Category: --> name missing and description missing but position OK:
![category](https://cloud.githubusercontent.com/assets/6297375/5719961/ea08b950-9b1d-11e4-98e6-ceac0993c450.png)

Forums
Forum: --> name missing  and description missing but position OK:
![forums](https://cloud.githubusercontent.com/assets/6297375/5720002/7b25a5f6-9b1e-11e4-91fb-7a80ce970862.png)

Users:
All users are imported. Only ranks have to be set-up.
![users](https://cloud.githubusercontent.com/assets/6297375/5720061/4ab8e3d2-9b1f-11e4-91e8-ff23afa0c7d3.png)

Ranks:
Name of rank is missing and some cleaning is necessary (my job)
![rank](https://cloud.githubusercontent.com/assets/6297375/5720101/e2d40fde-9b1f-11e4-8988-d67265f44401.png)

Frontpage:
Here is the front page display:
Apparently, the number of posts  
![frontpage](https://cloud.githubusercontent.com/assets/6297375/5720013/a23a8440-9b1e-11e4-9a46-eb80c05e2f52.png)
 
I'll send you the current MUBoard database after script running.
OK for the French translation. I'll modify it and let you know ASAP.
Thank you for the script.
Regards.
Pierre.

**Comment by PierreNau** [comment]
Hi Michael,
As promised on my github post, you’ll find in the attached the MUBoard database after running the script.
Regards.
Pierre.

**Comment by Portugao** [comment]
You're welcome.
Thx for the screenshots.

Hmmhmm....that is not so good.
Special chars in the title, descriptions and so on make it harder to import all correctly.

The ranks are not set in your dizkus tables, so i cannot improve that....

Which php version do you use and is the mysqli Extension activated on your server?

**Comment by PierreNau** [comment]
Hereafter my server details 
php version: 5.4.31
mysql version: 5.5.40-36.1
Apache version: 2.4.10
PHP extension : mysqli (activated)

OK for the ranks. I have to sort it out by myself on my dizkus tables.
What do you mean by chars (é, ê, è, à for example?)
Pierre.

**Comment by Portugao** [comment]
Ok. The technical aspect is not the cause of the missing title and so on.
I have to look....

Something like L'hotel.

**Comment by Portugao** [comment]
What about your users. For some of them i get no import?!
Which names are missing?

**Comment by Portugao** [comment]
Aspect of not set ranks for users.
For your understanding.
In your user table is for all users 'user_rank' set to 0.

**Comment by Portugao** [comment]
With the french translation you should wait until the script works like expected.

**Comment by PierreNau** [comment]
Oh I see!
I have 2 zikula install:
1.39 where dizkus cannot work
1.2.9, where dizkus is working. 
The number of users is different (more users on 1.2.9). So after importing the dizkus database on the 1.3.9 installation where MUBoard is (and to make the script running)  the dizkus table users (that of 1.2.9) is not matching the users table of 1.3.9.
That's reason why you got no import for some of them.
Maybe I'd better to equal the number of users.
With regard the ranks, I got rid of them. I'll set them up later on.
Regards.
Pierre.

**Comment by Portugao** [comment]
Nice to know. So the issues with users and ranks are cleared.
For the other issues with titles and so on i have to look.

Regards
Michael

**Comment by Portugao** [comment]
About categories.
In dizkus the categories have no description; it is an additional feature in MUBoard. :smile:

**Comment by PierreNau** [comment]
Indeed!

**Comment by Portugao** [comment]
It would be nice if you could test again with current repository.

Regards
Michael

**Comment by PierreNau** [comment]
Sorry Michael but I can’t connect to my DATABASE as it was possible previously??
I did not change any data.
Regards.
Pierre.

My server is OK.

**Comment by Portugao** [comment]
Yes. I implemented a check for that.
First idea is, your datas are wrong; sorry?! :smile:

**Comment by PierreNau** [comment]
With regard to the data, I cannot see any difference from the previous version.
Host
DB Name
Nom d'utilisateur
Password
With exactly the same value, I can't connect to the same database. What was possible previously.

**Comment by Portugao** [comment]
Yes. Previously there were no check and there were no access to the database. Now there is a check for find the reason why the titles, descriptions and texts do not find their way into the database.

Are you sure you have the correct datas; you speak of two databases?!

i ask because for me the import is working.

**Comment by PierreNau** [comment]
Hi Michael,
I've sorted it out my issue. I did a mistake in handling the databases.
The script worked properly as you can see here: http://www.jfk-assassinat.com/index.php?module=muboard&type=user&func=view&ot=category

Howerver, I don't understand why the number of posts of some users of the DIZKUS database are not implemented by the script . Example user christian is set to 0 what is odd for a major contributor?

Last suggestion why not to implement implement the total number of post to the bottom of the template instead of or in addition of the information (legend)?

Anyway, many thanks for your help.
Regards.
Pierre.

**Comment by Portugao** [comment]
Hi Pierre,

let me know the user ID of christian and i will have a look.

Ab out layout you could create an issue.

Regards
Michael

**Comment by PierreNau** [comment]
Michael,
christian id is 19.
Moreover I have no access to some forum because of the 5000 limit:

![5000](https://cloud.githubusercontent.com/assets/6297375/5735817/c23ad070-9bcc-11e4-81ef-c791e7136eed.png)

Is it possible to increase the 5000 limit to 10 000 or more?

Ok to create an issue about the layout.

Regards.
Pierre

**Comment by Portugao** [comment]
Hi Pierre, limit i changed to 10000.
You have to install again.

Regards
Michael

**Comment by Portugao** [comment]
In my user table of MUBoard after running import user christian(id 19) has 337 posts.
I have just tested....i'm a little bit confused.

**Comment by PierreNau** [comment]
Yes Michael that's correct. My explanation was poor.
What I meant is that the name of christian does not appear beside the 19 id as it should.
Thank you for the extension of the limit. That works pretty good!

**Comment by Portugao** [comment]
Fine! :smile:  You're welcome!

Is christian in the table of the users module?

**Comment by PierreNau** [comment]
No christian is not!! So I have to create this user with id 19 (not affected in the users table).
I'll check that and if it works I'll do the same process for similar cases.
I'll let you know.
Pierre.

**Comment by Portugao** [comment]
:+1:

**Comment by PierreNau** [comment]
Michael,
I did it for christian and all users in the same case. It worked perfectly. By now the forum is OK.
I just experienced something odd while posting the message. No problem whatsoever to post but I always this message to the top:

![error](https://cloud.githubusercontent.com/assets/6297375/5759419/1cf714a4-9cce-11e4-900d-63797fa27f43.png)

**Comment by Portugao** [comment]
Fine, that the import is like you wished.
To the messages:
The module wants to send a mail to users, that have subscribed a forum, if you post something within the forum.
Maybe there is no valid email adress in the users module for them, because MUBoard should get it from there.
If not i have to look at.

**Comment by PierreNau** [comment]
OK, but nobody has scribed to any forum as it was not online until now.
Maybe you peak of that users that suscribed formerly on the Dizkus forum? 

In addition, I have suscribed to all forums by clicking on the envelop icon to the right of each and I got the same message while posting. My email address is valid.

**Comment by Portugao** [comment]
Maybe you peak of that users that suscribed formerly on the Dizkus forum?
Yes. In the table 'z_dizkus_description' there are 51 entries that get imported by the import script.
I could delete this part of the script or make it optional to import the subscribers.

**Comment by Portugao** [comment]
I made a ticket for the case there is no valid email address.
See: https://github.com/Portugao/MUBoard/issues/72
