### ISSUE TITLE
What about not supported aspects and import

### ISSUE THREAD

**Issue by Portugao** [Portugao/MUBoard#67]
Not supported at this moment (no guarantee for completeness):

* Favorites
* Moderators
* Topic subscription

**Comment by Portugao** [comment]
@PierreNau
Please give feedback.

**Comment by PierreNau** [comment]
Thank you Michael.
I'll vive you feed-back tomorrow In the evening when I'm home.
Regards.
Pierre.

Envoyé de mon iPad

**Comment by Portugao** [comment]
:+1:

**Comment by PierreNau** [comment]
Hi Michael,
As promised, hereafter my feedback:
Sounds great as most of the dizkus functionalities are covered by the upgrade.
For those not supported:
- Moderators: --> can be handled via permission rules,
- Topic subscription and favorites --> not essential in my opinion for the moment.

By the way the French translation is ready for the MUBoard module. I'm going to send the files to you in a separate mail. As I'm not a developer, that is my contribution to the module.
Many thanks for your time and work.
Regards.
Pierre.

**Comment by Portugao** [comment]
Nice to hear that the not supported functionalities can wait.
Many thanks for the french translation, that i will integrate if i got.
