### ISSUE TITLE
After import we get error messages depending on subscriptions

### ISSUE THREAD

**Issue by Portugao** [Portugao/MUBoard#72]
It seems these error messages depend on the imported subscriber datas.
What to do?

**Comment by Portugao** [comment]
@PierreNau
Please check now if the message are gone if you create a posting.
Regards
Michael

**Comment by Portugao** [comment]
Have to reopen. That does not work.

**Comment by Portugao** [comment]
Like the updated title of this issue we get this issue depending on the imported subscriber datas from 'z_dizkus_subscription'.

Easiest way would be to delete the subscriber import, so users have to subscribe again.
What do you think, @PierreNau ?

Regards
Michael

**Comment by PierreNau** [comment]
Yes Michael I agree with your proposal that "the easiest way would be to delete the subscriber import, so users have to subscribe again".
Regards.
Pierre.

**Comment by Portugao** [comment]
Ok. Cleared.
I will do.

Hope this will really solve this issue.

Regards
Michael

**Comment by Portugao** [comment]
Done!
Please have a look. You could clear the table muboard_abo.

Regards
Michael

**Comment by PierreNau** [comment]
Ok Michael! Just applied truncate to the muboard_abo table. That works. No error message whatsoever!
Many thanks.
Pierre.

**Comment by Portugao** [comment]
Fine!
You're welcome.
