### ISSUE TITLE
Complete french translation

### ISSUE THREAD

**Issue by Portugao** [Portugao/MUBoard#73]
@PierreNau
Hi Pierre,

it would be fine if you could complete the french translation. :smile: 

Then i could add it to the repository and publish version 1.1.0.

**Comment by Portugao** [comment]
I have committed new pot file now.

**Comment by PierreNau** [comment]
Michael,
Done!
I sent the files to your email address (MU(t) Beratung Internet)
I'll do the same for MUImage and MUflash ASAP. I'll let you know. 
Pierre.

**Comment by Portugao** [comment]
Great.
Many thanks for your work.

Regards
Michael
