### ISSUE TITLE
In German: Icon-Pfade wenn MUBoard im Unterverzeichnis stimmen nicht und werden nicht erkannt

### ISSUE THREAD

**Issue by AlexL777** [Portugao/MUBoard#77]
Ich hoffe, dass ich hier auch auf Deutsch eine Frage stellen kann, denn ich es so verstanden habe, dass das Modul von einem deutschen Entwickler ist oder :)

Ich habe ein Problem mit dem MuBoard auf meiner Unterverzeichnis-Installation. Die Icon-Pfade im Frontend werden nicht richtig gesetzt bzw. erkannt und so zeigt mir das Board die Icons nicht an. Meine Installation ist unter http://wpzweinull.ch/cms/zikula13/muboard

Ob man mir so helfen kann?! Ich habe ansonsten Zikula 1.3.10, PHP 5.5 und die letzte mySQL-Version auf dem Server, falls es helfen sollte. Freue mich über die baldige Hilfestellung. Vielen Dank im Vorfeld.

In Englisch:

I hope that I can make in German a question here, as I understand it so that the module by a German developer or :)

I have a problem with the MuBoard on my subdirectory installation. The Icon-paths in the front end will not be set or detected correctly, thus showing me the board of the icons not. My installation is under http://wpzweinull.ch/cms/zikula13/muboard

Whether you can help me so ?! I have otherwise Zikula 1.3.10, PHP 5.5 and the latest version of MySQL on the server, if it would help. I appreciate the speedy assistance. Thank you in advance.

**Comment by Portugao** [comment]
Yo, ist ein Bug.

**Comment by AlexL777** [comment]
OK, vielen Dank für die schnelle Rückmeldung. Dann weiss ich es auch. Mir ist es nur aufgefallen. Früher bei der allerersten Zikula 1.3 Installation hatte ich das nicht, warum auch immer und damals war es wahrscheinlich auf einer Subdomain.

**Comment by Portugao** [comment]
Das wird ja hier:
http://support.zikula.de/module-CMS_Support_Forum-viewtopic-topic-31447-start-0.htm#pid149538
von Axel erklärt.
Es liegt daran, dass Deine Installation in einem Unterverzeichnis Deiner Domain aufgerufen wird.

**Comment by AlexL777** [comment]
Ja, das war ich heute im Support-Forum und so dachte ich es mir auch, weil die Pfade der Icons zur Hauptdomain Wpzweinull.ch und nicht zu Wpzwienull.ch/cms/zikula13 gesetzt wurden. Hm..kann ich es selbst reparieren, indem in einer bestimmten Datei die Pfade anpasse oder wäre es für mich als Hobby-Zikula-Nutzer nicht möglich?! Und welche Datei wäre es?

**Comment by AlexL777** [comment]
Habe das problem so eben lösen können :) Ich habe das Verzeichnis /images ins Root-Verzeichnis der Domain Wpzweinull.ch hochgeladen und sieh da, alle Icons sind an Ort und Stelle und das kann ich gleich im Support-Forum durchgeben, falls es noch jemand haben sollte. Also alles wieder gut!!

**Comment by Portugao** [comment]
:+1:
