### ISSUE TITLE
Memory overflow with very many postings, part 2

### ISSUE THREAD

**Issue by rmaiwald** [Portugao/MUBoard#81]
Issue #80 is fixed, but there is still at least one more memory hog.

In templates/user/forum/include_displayItemListMany.tpl I found "{$item.posting|@count}". Replacing it with "{$item.id|muboardGetNumberOfPostingsOfForum}" does not help, because the controller has already read all posting contents for all forums in all categories. :-(

Regards
Reiner

**Comment by Portugao** [comment]
Will have a look as soon as possible......

**Comment by Portugao** [comment]
This {$item.id|muboardGetNumberOfPostingsOfForum} should work now.
@rmaiwald 
Please have a try!

**Comment by rmaiwald** [comment]
Even if detail and bottom statistics are disabled, forums with very meny postings result in memory overflow. I found several more places that should be reviewed and fixed.

1. Header statistics cannot not be disabled in templates/user/category/display.tpl, templates/user/forum/display.tpl and templates/user/posting/include_displayItemListMany.tpl.
2. Several functions in lib/MUBoard/Util/View.php read all items (postings) and count them in stead of selecting the number of items from the database: getIssuesOfCategory(), getPostingsOfCategory(), getIssuesOfForum(), getAnswersOfPosting(), getLastAnswer().
3. Typo in lib/MUBoard/Entity/Repository/Posting.php (getNumberPostingsOfForm --> getNumberPostingsOfForum).

**Comment by Portugao** [comment]
1. For that you should open a feature request.
2. Will have a look.
3.Is fixed with https://github.com/Portugao/MUBoard/commit/2822a1c4f4d9ff9b99922c09d4102568ed3c6dea

**Comment by Portugao** [comment]
Further performance optimization will get its place in a new version for Zikula 1.5.x.
So I close this. See also https://github.com/Portugao/MUBoard/issues/83.
